export const actionTypes = {
  IS_LOADING: 'IS_LOADING',
  HAS_ERROR: 'HAS_ERROR',
  FETCH_HACKERS_SUCCESS: 'FETCH_HACKERS_SUCCESS',
  FETCH_HACKERS_FAILED: 'FETCH_HACKERS_FAILED',
  FETCH_HACKER_SUCCESS: 'FETCH_HACKER_SUCCESS',
  FETCH_HACKER_FAILED: 'FETCH_HACKER_FAILED',
  USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAIL: 'USER_REGISTER_FAIL'
};
