export const actionTypes = {
  IS_LOADING: 'IS_LOADING',
  HAS_ERROR: 'HAS_ERROR',
  FETCH_HACKERS_SUCCESS: 'FETCH_HACKERS_SUCCESS',
  FETCH_HACKERS_FAILED: 'FETCH_HACKERS_FAILED',
  FETCH_HACKER_SUCCESS: 'FETCH_HACKER_SUCCESS',
  FETCH_HACKER_FAILED: 'FETCH_HACKER_FAILED'
};
